# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
