# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaces', '0004_removing_null_true_of_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
